version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket cristhian-lambda-pipeline --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml
