version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Ejecutando Test"
      - ./gradlew build
  build:
    commands:
      - echo start build
      - sam build
      - echo start package
      - sam package --s3-bucket cristhian-lambda-pipeline --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - outputSamTemplate.yaml