version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - ./gradlew clean buildZip
      - sam package
        --template-file template.yaml
        --output-template-file outputSamTemplate.yaml
        --s3-bucket cristhian-lambda-pipeline
artifacts:
  files:
    - outputSamTemplate.yaml