AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  Stage:
    Type: String
    Description: Stage name to deploy resources to demo
    AllowedValues:
      - dev
      - qa
      - prod

  AppName:
     Type: String
     Default: app-user

Globals:
  Function:
    Runtime: java11
    Timeout: 60
    MemorySize: 512
    AutoPublishAlias: live
    ReservedConcurrentExecutions: 30
    Environment:
        Variables:
            DB_MIGRATION: false
            ENV: !Sub "${Stage}"

Resources:

  UserDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TableName: "USER_OPS"
      AttributeDefinitions:
        -   AttributeName: ID_USER_PK
            AttributeType: N
      KeySchema:
        -   AttributeName: ID_USER_PK
            KeyType: HASH

  UserOpsDbChangeLogDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TableName: "USER_OPS_DBCHANGELOG"
      AttributeDefinitions:
        - AttributeName: changeId
          AttributeType: S
      KeySchema:
        - AttributeName: changeId
          KeyType: HASH


  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${Stage}-${AppName}-api"
      StageName: !Ref Stage
      TracingEnabled: true

  UserFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: UserFunctionApp
      CodeUri: "app"
      Handler: app.bank.functions.UserFunction::handleRequest
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserDynamoTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserOpsDbChangeLogDynamoTable
      Events:
        GetUser:
          Type: Api
          Properties:
            Method: GET
            Path: /user/{id}
            RestApiId:
              Ref: ApiGatewayApi
        GetUsers:
          Type: Api
          Properties:
            Method: GET
            Path: /user
            RestApiId:
              Ref: ApiGatewayApi
        AddUser:
          Type: Api
          Properties:
            Method: POST
            Path: /user
            RestApiId:
              Ref: ApiGatewayApi
        GetValidate:
          Type: Api
          Properties:
            Method: GET
            Path: /validate/{msg}
            RestApiId:
              Ref: ApiGatewayApi

Outputs:
  MyURLRest:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"

