openapi: 3.0.0
info:
  version: 1.0.0
  title: supplier-integration-api
paths:
  /user:
    get:
      operationId: UserFunction
      summary: "Find order"
      description: "Find order"
      x-amazon-apigateway-integration:
        httpMethod: POST
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserFunction.Arn}/invocations"
        timeoutInMillis: 29000
        type: "aws_proxy"
        responses:
          default:
            statusCode: "200"
      responses:
        200:
          description: "OK"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Bad Request"
        500:
          description: "Internal Server Error"
